"""catalogo tribunales

Revision ID: 497c8671178f
Revises: ceee1b5efc78
Create Date: 2026-08-26 17:17:05.515273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '497c8671178f'
down_revision: Union[str, None] = 'ceee1b5efc78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tribunales_catalogo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('competencia', sa.String(length=20), nullable=False),
    sa.Column('corte_id', sa.Integer(), nullable=False),
    sa.Column('corte_nombre', sa.String(length=120), nullable=False),
    sa.Column('tribunal_id', sa.Integer(), nullable=False),
    sa.Column('tribunal_nombre', sa.String(length=200), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competencia', 'corte_id', 'tribunal_id', name='uq_tribunales_catalogo_clave')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tribunales_catalogo')
    # ### end Alembic commands ###
