"""esquema inicial

Revision ID: ceee1b5efc78
Revises: 
Create Date: 2026-08-21 11:58:52.593219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ceee1b5efc78'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('causas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('competencia', sa.String(length=20), nullable=False),
    sa.Column('corte', sa.Integer(), nullable=False),
    sa.Column('tribunal', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=4), nullable=False),
    sa.Column('rol', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('rol_formateado', sa.String(length=40), nullable=False),
    sa.Column('caratula', sa.String(length=500), nullable=True),
    sa.Column('fecha_ingreso', sa.String(length=20), nullable=True),
    sa.Column('est_adm', sa.String(length=200), nullable=True),
    sa.Column('proceso', sa.String(length=300), nullable=True),
    sa.Column('ubicacion', sa.String(length=100), nullable=True),
    sa.Column('estado_proceso', sa.String(length=200), nullable=True),
    sa.Column('etapa', sa.String(length=300), nullable=True),
    sa.Column('tribunal_nombre', sa.String(length=200), nullable=True),
    sa.Column('estado_sync', sa.String(length=15), nullable=False),
    sa.Column('sync_iniciado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_ultima_sincronizacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ultimo_error', sa.String(length=2000), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("estado_sync IN ('Pendiente', 'Sincronizando', 'Completo', 'Error')", name='ck_causas_estado_sync'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competencia', 'corte', 'tribunal', 'tipo', 'rol', 'anio', name='uq_causas_clave_natural')
    )
    op.create_table('clientes_api',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('client_key_hash', sa.String(length=64), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_api_client_key_hash'), 'clientes_api', ['client_key_hash'], unique=True)
    op.create_table('cuadernos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('causa_id', sa.UUID(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['causa_id'], ['causas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('causa_id', 'numero', name='uq_cuadernos_causa_numero')
    )
    op.create_index(op.f('ix_cuadernos_causa_id'), 'cuadernos', ['causa_id'], unique=False)
    op.create_table('informacion_receptor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('causa_id', sa.UUID(), nullable=False),
    sa.Column('cuaderno_nombre', sa.String(length=300), nullable=True),
    sa.Column('datos_retiro', sa.String(length=300), nullable=True),
    sa.Column('fecha_retiro', sa.String(length=60), nullable=True),
    sa.Column('estado', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['causa_id'], ['causas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('causa_id', 'cuaderno_nombre', 'fecha_retiro', name='uq_info_receptor_causa_cuad_fecha')
    )
    op.create_index(op.f('ix_informacion_receptor_causa_id'), 'informacion_receptor', ['causa_id'], unique=False)
    op.create_table('sync_job',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('causa_id', sa.UUID(), nullable=False),
    sa.Column('estado', sa.String(length=15), nullable=False),
    sa.Column('intentos', sa.Integer(), nullable=False),
    sa.Column('error_mensaje', sa.String(length=2000), nullable=True),
    sa.Column('encolado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('iniciado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finalizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("estado IN ('pendiente', 'en_progreso', 'completo', 'error')", name='ck_sync_job_estado'),
    sa.ForeignKeyConstraint(['causa_id'], ['causas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_job_causa_id'), 'sync_job', ['causa_id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes_api.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cliente_id', 'email', name='uq_usuarios_cliente_email')
    )
    op.create_index(op.f('ix_usuarios_cliente_id'), 'usuarios', ['cliente_id'], unique=False)
    op.create_table('documentos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('causa_id', sa.UUID(), nullable=False),
    sa.Column('cuaderno_id', sa.Integer(), nullable=True),
    sa.Column('categoria', sa.String(length=40), nullable=False),
    sa.Column('clave_logica', sa.String(length=160), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=160), nullable=False),
    sa.Column('ruta_archivo', sa.String(length=1000), nullable=False),
    sa.Column('hash_contenido_fila_padre', sa.String(length=64), nullable=True),
    sa.Column('referencia_origen', sa.String(length=300), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['causa_id'], ['causas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cuaderno_id'], ['cuadernos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('causa_id', 'clave_logica', name='uq_documentos_causa_clave_logica')
    )
    op.create_index(op.f('ix_documentos_causa_id'), 'documentos', ['causa_id'], unique=False)
    op.create_index(op.f('ix_documentos_cuaderno_id'), 'documentos', ['cuaderno_id'], unique=False)
    op.create_table('exhortos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cuaderno_id', sa.Integer(), nullable=False),
    sa.Column('rol_origen', sa.String(length=30), nullable=True),
    sa.Column('tipo_exhorto', sa.String(length=60), nullable=True),
    sa.Column('fecha_ordena_exhorto', sa.String(length=60), nullable=True),
    sa.Column('fecha_ingreso_exhorto', sa.String(length=60), nullable=True),
    sa.Column('tribunal_destino', sa.String(length=300), nullable=True),
    sa.Column('estado_exhorto', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['cuaderno_id'], ['cuadernos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cuaderno_id', 'rol_origen', 'tipo_exhorto', name='uq_exhortos_cuaderno_rol_tipo')
    )
    op.create_index(op.f('ix_exhortos_cuaderno_id'), 'exhortos', ['cuaderno_id'], unique=False)
    op.create_table('litigantes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cuaderno_id', sa.Integer(), nullable=False),
    sa.Column('participante', sa.String(length=60), nullable=True),
    sa.Column('rut', sa.String(length=15), nullable=True),
    sa.Column('persona', sa.String(length=10), nullable=True),
    sa.Column('razon_social', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['cuaderno_id'], ['cuadernos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cuaderno_id', 'participante', 'rut', name='uq_litigantes_cuaderno_part_rut')
    )
    op.create_index(op.f('ix_litigantes_cuaderno_id'), 'litigantes', ['cuaderno_id'], unique=False)
    op.create_table('notificaciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cuaderno_id', sa.Integer(), nullable=False),
    sa.Column('rol', sa.String(length=30), nullable=True),
    sa.Column('estado_notificacion', sa.String(length=60), nullable=True),
    sa.Column('tipo_notificacion', sa.String(length=60), nullable=True),
    sa.Column('fecha_tramite', sa.String(length=60), nullable=True),
    sa.Column('tipo_part', sa.String(length=60), nullable=True),
    sa.Column('nombre', sa.String(length=300), nullable=True),
    sa.Column('tramite', sa.String(length=300), nullable=True),
    sa.Column('observacion_fallida', sa.String(length=500), nullable=True),
    sa.Column('contenido_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['cuaderno_id'], ['cuadernos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cuaderno_id', 'contenido_hash', name='uq_notificaciones_cuaderno_hash')
    )
    op.create_index(op.f('ix_notificaciones_cuaderno_id'), 'notificaciones', ['cuaderno_id'], unique=False)
    op.create_table('tokens_acceso',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expira_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revocado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tokens_acceso_token_hash'), 'tokens_acceso', ['token_hash'], unique=True)
    op.create_index(op.f('ix_tokens_acceso_usuario_id'), 'tokens_acceso', ['usuario_id'], unique=False)
    op.create_table('anexos_causa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('causa_id', sa.UUID(), nullable=False),
    sa.Column('documento_id', sa.UUID(), nullable=True),
    sa.Column('fecha', sa.String(length=60), nullable=True),
    sa.Column('referencia', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['causa_id'], ['causas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('causa_id', 'referencia', 'fecha', name='uq_anexos_causa_ref_fecha')
    )
    op.create_index(op.f('ix_anexos_causa_causa_id'), 'anexos_causa', ['causa_id'], unique=False)
    op.create_table('escritos_resolver',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cuaderno_id', sa.Integer(), nullable=False),
    sa.Column('documento_id', sa.UUID(), nullable=True),
    sa.Column('fecha_ingreso', sa.String(length=60), nullable=True),
    sa.Column('tipo_escrito', sa.String(length=300), nullable=True),
    sa.Column('solicitante', sa.String(length=300), nullable=True),
    sa.Column('contenido_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['cuaderno_id'], ['cuadernos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cuaderno_id', 'contenido_hash', name='uq_escritos_cuaderno_hash')
    )
    op.create_index(op.f('ix_escritos_resolver_cuaderno_id'), 'escritos_resolver', ['cuaderno_id'], unique=False)
    op.create_table('exhortos_rol_destino',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exhorto_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['exhorto_id'], ['exhortos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exhorto_id', 'nombre', name='uq_exhorto_rol_destino_nombre')
    )
    op.create_index(op.f('ix_exhortos_rol_destino_exhorto_id'), 'exhortos_rol_destino', ['exhorto_id'], unique=False)
    op.create_table('movimientos_historia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cuaderno_id', sa.Integer(), nullable=False),
    sa.Column('folio', sa.Integer(), nullable=False),
    sa.Column('documento_id', sa.UUID(), nullable=True),
    sa.Column('etapa', sa.String(length=300), nullable=True),
    sa.Column('tramite', sa.String(length=300), nullable=True),
    sa.Column('descripcion_tramite', sa.String(length=1000), nullable=True),
    sa.Column('fecha_tramite', sa.String(length=60), nullable=True),
    sa.Column('foja', sa.Integer(), nullable=True),
    sa.Column('hash_contenido', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['cuaderno_id'], ['cuadernos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cuaderno_id', 'folio', name='uq_historia_cuaderno_folio')
    )
    op.create_index(op.f('ix_movimientos_historia_cuaderno_id'), 'movimientos_historia', ['cuaderno_id'], unique=False)
    op.create_table('exhortos_rol_destino_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rol_destino_id', sa.Integer(), nullable=False),
    sa.Column('documento_id', sa.UUID(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.String(length=60), nullable=True),
    sa.Column('referencia', sa.String(length=300), nullable=True),
    sa.Column('tramite', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos.id'], ),
    sa.ForeignKeyConstraint(['rol_destino_id'], ['exhortos_rol_destino.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rol_destino_id', 'orden', name='uq_exhorto_item_rol_destino_orden')
    )
    op.create_index(op.f('ix_exhortos_rol_destino_items_rol_destino_id'), 'exhortos_rol_destino_items', ['rol_destino_id'], unique=False)
    op.create_table('movimientos_historia_anexos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('movimiento_id', sa.Integer(), nullable=False),
    sa.Column('documento_id', sa.UUID(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.String(length=60), nullable=True),
    sa.Column('referencia', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos.id'], ),
    sa.ForeignKeyConstraint(['movimiento_id'], ['movimientos_historia.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('movimiento_id', 'orden', name='uq_historia_anexo_movimiento_orden')
    )
    op.create_index(op.f('ix_movimientos_historia_anexos_movimiento_id'), 'movimientos_historia_anexos', ['movimiento_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movimientos_historia_anexos_movimiento_id'), table_name='movimientos_historia_anexos')
    op.drop_table('movimientos_historia_anexos')
    op.drop_index(op.f('ix_exhortos_rol_destino_items_rol_destino_id'), table_name='exhortos_rol_destino_items')
    op.drop_table('exhortos_rol_destino_items')
    op.drop_index(op.f('ix_movimientos_historia_cuaderno_id'), table_name='movimientos_historia')
    op.drop_table('movimientos_historia')
    op.drop_index(op.f('ix_exhortos_rol_destino_exhorto_id'), table_name='exhortos_rol_destino')
    op.drop_table('exhortos_rol_destino')
    op.drop_index(op.f('ix_escritos_resolver_cuaderno_id'), table_name='escritos_resolver')
    op.drop_table('escritos_resolver')
    op.drop_index(op.f('ix_anexos_causa_causa_id'), table_name='anexos_causa')
    op.drop_table('anexos_causa')
    op.drop_index(op.f('ix_tokens_acceso_usuario_id'), table_name='tokens_acceso')
    op.drop_index(op.f('ix_tokens_acceso_token_hash'), table_name='tokens_acceso')
    op.drop_table('tokens_acceso')
    op.drop_index(op.f('ix_notificaciones_cuaderno_id'), table_name='notificaciones')
    op.drop_table('notificaciones')
    op.drop_index(op.f('ix_litigantes_cuaderno_id'), table_name='litigantes')
    op.drop_table('litigantes')
    op.drop_index(op.f('ix_exhortos_cuaderno_id'), table_name='exhortos')
    op.drop_table('exhortos')
    op.drop_index(op.f('ix_documentos_cuaderno_id'), table_name='documentos')
    op.drop_index(op.f('ix_documentos_causa_id'), table_name='documentos')
    op.drop_table('documentos')
    op.drop_index(op.f('ix_usuarios_cliente_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_sync_job_causa_id'), table_name='sync_job')
    op.drop_table('sync_job')
    op.drop_index(op.f('ix_informacion_receptor_causa_id'), table_name='informacion_receptor')
    op.drop_table('informacion_receptor')
    op.drop_index(op.f('ix_cuadernos_causa_id'), table_name='cuadernos')
    op.drop_table('cuadernos')
    op.drop_index(op.f('ix_clientes_api_client_key_hash'), table_name='clientes_api')
    op.drop_table('clientes_api')
    op.drop_table('causas')
    # ### end Alembic commands ###
